version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: MatiasUCD
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.simple
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./apps/backend/.env.production
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.simple
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./apps/frontend/.env.production
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  ml-api:
    build:
      context: .
      dockerfile: ./data/Dockerfile.production
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=production
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:

volumes:
  postgres_data: