name: Deploy v2 with Nginx

on:
  push:
    branches:
      - main
      - docker/try-matias
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build backend
      run: npm run build:backend
    
    - name: Build frontend  
      run: npm run build:frontend
    
    - name: Run backend tests
      run: npm run test:backend
      env:
        NODE_ENV: test
    
    - name: Run frontend tests
      run: npm run test:frontend
      env:
        NODE_ENV: test
    
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Only run if tests pass
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Navigate to the project directory in /tmp
          cd /tmp/TaxiApp
          
          # Pull latest changes
          git pull origin docker/try-matias
          
          # Make deployment script executable
          chmod +x deploy-v2.sh
          
          # Run deployment v2 with sudo password
          export SUDO_PASSWORD=${{ secrets.SERVER_PASSWORD }}
          ./deploy-v2.sh